### PR TITLE
set rc.regex=no - we don't want to use regex

### LINKED ISSUE #98: Test failures using taskwarrior 2.4.4
```
======================================================================
FAIL: taskw.test.test_datas.TestDBShellout.test_filtering_brace
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/ybasldb42n05g7b7jsxz2f40jy3bwyj3-python2.7-nose-1.3.4/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/nix-build-python2.7-taskw-1.0.3.drv-0/taskw-1.0.3/taskw/test/test_datas.py", line 374, in test_filtering_brace
    eq_(len(tasks), 1)
AssertionError: 2 != 1

======================================================================
FAIL: taskw.test.test_datas.TestDBShellout.test_filtering_plus
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/ybasldb42n05g7b7jsxz2f40jy3bwyj3-python2.7-nose-1.3.4/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/nix-build-python2.7-taskw-1.0.3.drv-0/taskw-1.0.3/taskw/test/test_datas.py", line 393, in test_filtering_plus
    eq_(len(tasks), 1)
AssertionError: 3 != 1

======================================================================
FAIL: taskw.test.test_datas.TestDBShellout.test_filtering_qmark
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/ybasldb42n05g7b7jsxz2f40jy3bwyj3-python2.7-nose-1.3.4/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/nix-build-python2.7-taskw-1.0.3.drv-0/taskw-1.0.3/taskw/test/test_datas.py", line 423, in test_filtering_qmark
    eq_(tasks[0]['id'], 2)
AssertionError: 1 != 2

======================================================================
FAIL: taskw.test.test_datas.TestDBShellout.test_filtering_question_mark
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/ybasldb42n05g7b7jsxz2f40jy3bwyj3-python2.7-nose-1.3.4/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/nix-build-python2.7-taskw-1.0.3.drv-0/taskw-1.0.3/taskw/test/test_datas.py", line 451, in test_filtering_question_mark
    eq_(len(tasks), 1)
AssertionError: 2 != 1
```

### PR DESCRIPTION
**Pull request by EdwardBetts**
Fixes #98

### CODE REVIEW

**Comment by ralphbean** [comment]
Hm, try running the test suite with ``tox``.  It should attempt to run the tests on multiple python versions and against multiple versions of the 'taskwarrior' binary (to see if we're backwards compatible).

The change here makes those tests fail for task-2.4.x and task-2.5.x.  Any ideas?

**Comment by EdwardBetts** [comment]
According to https://taskwarrior.org/docs/searching.html the rc.regex setting was added in task 2.4

It seems like the solution will be to add rc.regex=off for taskwarrior 2.4 and above.

I've just run tox, it is busy compiling various versions of taskwarrior.

**Comment by EdwardBetts** [comment]
I ran tox, the problem only happens with task 2.4.4, which happens to be the current version in Debian unstable. I've updated the bug report.

**Comment by ralphbean** [comment]
Thanks for looking into it @EdwardBetts :)

**Pull request closed without merging**
