### PR TITLE
Run tests using multiples versions of Taskwarrior on Travis.ci

### LINKED ISSUE #72: Alter test harness to add integration tests verifying behavior under multiple versions of Taskwarrior
Although previously Taskwarrior was (as far as I can tell) fairly predictable, there have been substantial changes in the latest version of Taskwarrior.  In the interest of completion, I suggest that we (read: at this point -- "I") verify Taskwarrior's behavior under at least both 2.3.x and 2.4.x.

### PR DESCRIPTION
**Pull request by coddingtonbear**
Behold the glory that is this build: https://travis-ci.org/ralphbean/taskw/builds/47302626.

Fixes #72.

:pray:

### CODE REVIEW

**Comment by ralphbean** [comment]
Wow.

**Comment by ralphbean** [comment]
This is just awesome.  Thanks @coddingtonbear!

**Comment by coddingtonbear** [comment]
Yeah! I'm really fantastically surprised at how easily it turned out, actually -- I kind of thought this was going to be complicated.

I think most of the v2.4.0 failures are to be expected -- and I'm very curious to see what failures remain if you merged this branch into there, but the failure on Python 3.3 + Taskwarrior 2.2 was a little surprising.

**Comment by ralphbean** [comment]
Yup.  I expect we'll do a lot better with taskwarrior-2.4.1 too (I thought it was going to be out yesterday).

**Pull request merged**
