### PR TITLE
Update taskwarrior git repo url

### PR DESCRIPTION
**Pull request by Fongshway**

### CODE REVIEW

**Review by ralphbean — APPROVED** [review]

**Comment by Fongshway** [comment]
Are we okay with removing python 2.6 from the test matrix to get tests to pass?

**Comment by ralphbean** [comment]
> Are we okay with removing python 2.6 from the test matrix to get tests to pass?

Yeah, sounds good to me.  Can you add it to this PR?

**Comment by Fongshway** [comment]
🎉 tests are green!

On a separate note, would you be interested in additional PRs? I've been playing around with `taskw` on my own fork (https://github.com/Fongshway/taskw) as a way to teach myself more about python and maintaining an open source project, and I would love to give back to this project if possible!

**Comment by ralphbean** [comment]
> interested in additional PRs?

In general, yes!  But, I've had very little time to give to maintaining this project over the last year.  Check with @ryneeverett, who has been the most active owner for this and `bugwarrior`.

**Comment by Fongshway** [comment]
Sounds good, and thank you for maintaining this project!

**Pull request merged**
