### PR TITLE
Adding two new tests that ensures we can store and retrieve values by URL UDA, and that filtering works properly

### PR DESCRIPTION
**Pull request by coddingtonbear**

### CODE REVIEW

**Comment by ralphbean** [comment]
I haven't been able to find a way around the search-by-URL issue yet.  Have you mentioned it to @pbeckingham yet, or should I bring it up?

**Comment by coddingtonbear** [comment]
Hrm, I kind of assumed that this was something somebody else bumped into already; I haven't said anything to him about it.

**Comment by coddingtonbear** [comment]
Oh!  And I think you might be able to omit the version check in `taskw.utils.encode_query.wrap`; from my brief brief brief tests, it looked like the "Mismatched parens" error you were bumping into is that we were using `<field>.any` followed immediately by parens, but if you add spaces on the inside of the parens, everything worked fine.

**Comment by ralphbean** [comment]
> I think you might be able to omit the version check

Excellent!

**Comment by ralphbean** [comment]
Ah.  Try this:

```diff
diff --git a/taskw/test/test_datas.py b/taskw/test/test_datas.py
index e26cafe..c0fb31a 100644
--- a/taskw/test/test_datas.py
+++ b/taskw/test/test_datas.py
@@ -577,7 +577,7 @@ class TestDBShellout(_BaseTestDB):
             someurl=arbitrary_url,
         )
         results = self.tw.filter_tasks({
-            'someurl': arbitrary_url
+            'someurl.is': arbitrary_url
         })
         eq_(len(results), 1)
         task = results[0]
```

It works!  The question for me is -- do we want to alter the test like this (and alter bugwarrior to match) or do we want taskw to insert the ``.is`` behind the scenes so that things "just work" for taskw users.

**Comment by coddingtonbear** [comment]
Hrm!  Neat -- I hadn't considered adding `.is` following the filter specification.

I don't know if we should do this automatically, honestly, since the behavior of `.is` is a little different from the default, but it does definitely help with Bugwarrior.  ¯\_(ツ)_/¯

**Comment by coddingtonbear** [comment]
I mean, we could change the key for the user if the value has a `/` in it and raise a `warning.warn` when the transformation occurs, but I think that might add future confusion if at some point it becomes possible to use the bare (without `.is`) key, or somebody tries to search for a  task like "Go to the grocery/convenience store" by using ``{'description': 'grocery/convenience store'}``.

**Comment by ralphbean** [comment]
OTOH, failing without the ``.is`` is what taskwarrior does beneath us.  We might as well just expose the error to the taskw user as-is.

**Comment by coddingtonbear** [comment]
Yeah, I kind of agree; we should probably link @pbeckingham to this conversation, actually.

**Comment by ralphbean** [comment]
OK!  Issues raised here "fixed" in 8432a21 and 1387ed3.

I think now we're just waiting on the numeric uda issue to be fixed in task-2.4.1 for bugwarrior to work (the trac service and others that search by numeric udas don't work with task-2.4.0).

**Pull request merged**
